name = "flash"
version = "2.0.0"
description = "Gleam package enabling structured logging in both Erlang and JavaScript environments"
licenses = ["BSD-2-Clause-Patent"]
repository = { type = "github", user = "larzconwell", repo = "flash" }

gleam = ">= 1.13.0"

[dependencies]
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
