name = "flash"
version = "1.0.0"
description = "Gleam package enabling structured logging in both Erlang and JavaScript environments"
licenses = ["BSD-2-Clause-Patent"]
repository = { type = "github", user = "larzconwell", repo = "flash" }

gleam = ">= 1.0.0"

[dependencies]
gleam_stdlib = "~> 0.36"
birl = "~> 1.5"
gleam_json = ">= 1.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
